"""2nd version

Revision ID: 0e414e0ae541
Revises: 270654c2a898
Create Date: 2024-02-20 21:19:07.450115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e414e0ae541'
down_revision = '270654c2a898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_pressures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('systolic', sa.SmallInteger(), nullable=True),
    sa.Column('diastolic', sa.SmallInteger(), nullable=True),
    sa.Column('pulse', sa.SmallInteger(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_pressures_id'), 'saved_pressures', ['id'], unique=False)
    op.create_table('saved_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('joined', sa.Date(), nullable=True),
    sa.Column('deleted', sa.Date(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_users_id'), 'saved_users', ['id'], unique=False)
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('new_users', sa.SmallInteger(), nullable=True),
    sa.Column('deleted_users', sa.SmallInteger(), nullable=True),
    sa.Column('active_users', sa.SmallInteger(), nullable=True),
    sa.Column('super_active_users', sa.SmallInteger(), nullable=True),
    sa.Column('paincases', sa.Integer(), nullable=True),
    sa.Column('druguses', sa.Integer(), nullable=True),
    sa.Column('pressures', sa.Integer(), nullable=True),
    sa.Column('medications', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistics_id'), 'statistics', ['id'], unique=False)
    op.create_table('pressures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('systolic', sa.SmallInteger(), nullable=True),
    sa.Column('diastolic', sa.SmallInteger(), nullable=True),
    sa.Column('pulse', sa.SmallInteger(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pressures_id'), 'pressures', ['id'], unique=False)
    op.add_column('users', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.drop_index(op.f('ix_pressures_id'), table_name='pressures')
    op.drop_table('pressures')
    op.drop_index(op.f('ix_statistics_id'), table_name='statistics')
    op.drop_table('statistics')
    op.drop_index(op.f('ix_saved_users_id'), table_name='saved_users')
    op.drop_table('saved_users')
    op.drop_index(op.f('ix_saved_pressures_id'), table_name='saved_pressures')
    op.drop_table('saved_pressures')
    # ### end Alembic commands ###
