"""Added last_notified column

Revision ID: 5efbb3eacc87
Revises: 
Create Date: 2022-05-29 23:47:59.949743+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5efbb3eacc87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_notified', sa.DateTime(), nullable=True))
    op.execute("UPDATE users SET last_notified=DATETIME(ROUND(1554076800 / 1000), 'unixepoch')")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_notified')
    # ### end Alembic commands ###
