"""add user_name and first_name to User

Revision ID: 35a25a7b2ff0
Revises: 74000257bbaa
Create Date: 2022-06-22 00:33:44.711101+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a25a7b2ff0'
down_revision = '74000257bbaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('user_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
