"""remove bool medecine taken from PainCase

Revision ID: 76c1676d3cec
Revises: 5efbb3eacc87
Create Date: 2022-05-30 21:35:28.613089+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c1676d3cec'
down_revision = '5efbb3eacc87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pains', 'medecine')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pains', sa.Column('medecine', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
