"""add columns to PainCase

Revision ID: 74000257bbaa
Revises: 76c1676d3cec
Create Date: 2022-05-30 22:28:28.102228+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74000257bbaa'
down_revision = '76c1676d3cec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pains', sa.Column('durability', sa.Integer(), nullable=True))
    op.add_column('pains', sa.Column('intensity', sa.Integer(), nullable=True))
    op.add_column('pains', sa.Column('aura', sa.Boolean(), nullable=True))
    op.add_column('pains', sa.Column('symptoms', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pains', 'symptoms')
    op.drop_column('pains', 'aura')
    op.drop_column('pains', 'intensity')
    op.drop_column('pains', 'durability')
    # ### end Alembic commands ###
