"""users.paincases, .driguses and .drugs on-cascade delete

Revision ID: 270654c2a898
Revises: 2ed9949d62c5
Create Date: 2023-08-19 20:13:48.459205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '270654c2a898'
down_revision = '2ed9949d62c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('drugs_owner_id_fkey', 'drugs', type_='foreignkey')
    op.create_foreign_key('drugs_owner_id_fkey', 'drugs', 'users', ['owner_id'], ['telegram_id'], ondelete='CASCADE')
    op.drop_constraint('druguses_paincase_id_fkey', 'druguses', type_='foreignkey')
    op.drop_constraint('druguses_owner_id_fkey', 'druguses', type_='foreignkey')
    op.create_foreign_key('druguses_owner_id_fkey', 'druguses', 'users', ['owner_id'], ['telegram_id'], ondelete='CASCADE')
    op.create_foreign_key('druguses_paincase_id_fkey', 'druguses', 'pains', ['paincase_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('pains_owner_id_fkey', 'pains', type_='foreignkey')
    op.create_foreign_key('pains_owner_id_fkey', 'pains', 'users', ['owner_id'], ['telegram_id'], ondelete='CASCADE')
    op.drop_constraint('saved_druguses_paincase_id_fkey', 'saved_druguses', type_='foreignkey')
    op.create_foreign_key('saved_druguses_paincase_id_fkey', 'saved_druguses', 'saved_pains', ['paincase_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('saved_druguses_paincase_id_fkey', 'saved_druguses', type_='foreignkey')
    op.create_foreign_key('saved_druguses_paincase_id_fkey', 'saved_druguses', 'saved_pains', ['paincase_id'], ['id'])
    op.drop_constraint('pains_owner_id_fkey', 'pains', type_='foreignkey')
    op.create_foreign_key('pains_owner_id_fkey', 'pains', 'users', ['owner_id'], ['telegram_id'])
    op.drop_constraint('druguses_paincase_id_fkey', 'druguses', type_='foreignkey')
    op.drop_constraint('druguses_owner_id_fkey', 'druguses', type_='foreignkey')
    op.create_foreign_key('druguses_paincase_id_fkey', 'druguses', 'pains', ['paincase_id'], ['id'])
    op.create_foreign_key('druguses_owner_id_fkey', 'druguses', 'users', ['owner_id'], ['telegram_id'])
    op.drop_constraint('drugs_owner_id_fkey', 'drugs', type_='foreignkey')
    op.create_foreign_key('drugs_owner_id_fkey', 'drugs', 'users', ['owner_id'], ['telegram_id'])
    # ### end Alembic commands ###
