"""Initial migration

Revision ID: 2ed9949d62c5
Revises: 
Create Date: 2023-08-12 17:48:31.006390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed9949d62c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_pains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('durability', sa.SmallInteger(), nullable=True),
    sa.Column('intensity', sa.SmallInteger(), nullable=True),
    sa.Column('aura', sa.Boolean(), nullable=True),
    sa.Column('provocateurs', sa.String(), nullable=True),
    sa.Column('symptoms', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_pains_id'), 'saved_pains', ['id'], unique=False)
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('last_notified', sa.DateTime(), nullable=True),
    sa.Column('notify_every', sa.SmallInteger(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('joined', sa.Date(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('utc_notify_at', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('drugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('daily_max', sa.Float(), nullable=True),
    sa.Column('is_painkiller', sa.Boolean(), nullable=True),
    sa.Column('is_temp_reducer', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drugs_id'), 'drugs', ['id'], unique=False)
    op.create_table('pains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('durability', sa.SmallInteger(), nullable=True),
    sa.Column('intensity', sa.SmallInteger(), nullable=True),
    sa.Column('aura', sa.Boolean(), nullable=True),
    sa.Column('provocateurs', sa.String(), nullable=True),
    sa.Column('symptoms', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pains_id'), 'pains', ['id'], unique=False)
    op.create_table('saved_druguses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('amount', sa.String(), nullable=True),
    sa.Column('drugname', sa.String(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('paincase_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paincase_id'], ['saved_pains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_druguses_id'), 'saved_druguses', ['id'], unique=False)
    op.create_table('druguses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('amount', sa.String(), nullable=True),
    sa.Column('drugname', sa.String(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('paincase_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.telegram_id'], ),
    sa.ForeignKeyConstraint(['paincase_id'], ['pains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_druguses_id'), 'druguses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_druguses_id'), table_name='druguses')
    op.drop_table('druguses')
    op.drop_index(op.f('ix_saved_druguses_id'), table_name='saved_druguses')
    op.drop_table('saved_druguses')
    op.drop_index(op.f('ix_pains_id'), table_name='pains')
    op.drop_table('pains')
    op.drop_index(op.f('ix_drugs_id'), table_name='drugs')
    op.drop_table('drugs')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_saved_pains_id'), table_name='saved_pains')
    op.drop_table('saved_pains')
    # ### end Alembic commands ###
