"""last_name col in users

Revision ID: cee8be92e3d2
Revises: 0e414e0ae541
Create Date: 2024-03-06 00:03:26.385232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee8be92e3d2'
down_revision = '0e414e0ae541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('saved_users', 'last_name')
    # ### end Alembic commands ###
