stages:
  - check_vars
  - pull
  - build
  - copy_db
  - test
  - run

check_vars:
  stage: check_vars
  allow_failure: false
  when: manual
  script:
    - |
      if [ -z "$API_TOKEN" ] || [ -z "$RABBITMQ_USER" ] || [ -z "$RABBITMQ_PASS" ] || [ -z "$RABBITMQ_HOST" ] || [ -z "$MY_TG_ID" ] || [ -z "$POSTGRES_USER" ] || [ -z "$POSTGRES_PASS" ] || [ -z "$PAYMENTS_TOKEN_RU" ]; then
        echo "Error: Missing one or more required environment variables."
        exit 1
      fi

pull:
  stage: pull
  allow_failure: false
  when: manual
  needs:
    - check_vars
  script:
    - git config --global --add safe.directory /usr/migrebot
    - cd /usr/migrebot
    - git pull

build:
  stage: build
  allow_failure: false
  when: manual
  needs:
    - pull
  script:
    - cd /usr/migrebot
    - docker compose build

copy_db:
  stage: copy_db
  when: manual
  script:
    - if [ ! -f "/usr/migrebot/db/sql_app.db" ]; then
        cp /usr/migraine_stat/db/sql_app.db /usr/migrebot/db;
      else
        echo "The file already exists, skipping copy.";
      fi

test:
  stage: test
  when: manual
  script:
    - cd /usr/migrebot
    - docker compose up -d rabbitmq
    - docker compose run migrebot pytest

run:
  stage: run
  when: manual
  script:
    - cd /usr/migrebot
    - docker compose up -d migrebot
