workflow:
  rules:
    - if: ($API_TOKEN == null || $RABBITMQ_USER == null || $RABBITMQ_PASS == null || $RABBITMQ_HOST == null || $MY_TG_ID == null)
  script:
    - echo "Some of the env vars is null"
    - exit 1

stages:
  - pull
  - build
  - copy_db
  - test
  - deploy

pull:
  stage: pull
  script:
    - cd /usr/migrebot
    - git pull

build:
  stage: build
  when: manual
  script:
    - cd /usr/migrebot
    - docker compose up -d

copy_db:
  stage: copy_db
  when: manual
  rules:
    - exists:
        - '/usr/migrebot/db/sql_app.db'
      when: never
  script:
    - cp /usr/migraine_stat/db/sql_app.db /usr/migrebot/db

test:
  stage: test
  when: manual
  script:
    - docker exec -it migrebot sh -c 'pytest'

run:
  stage: run
  when: manual
  script:
    - docker exec -it migrebot sh -c 'python -m src.main'
