stages:
  - check_vars
  - pull
  - build
  - start_dbs
  - migration
  - test
  - run

check_vars:
  stage: check_vars
  when: manual
  script:
    - |
      if [ -z "$API_TOKEN" ] || [ -z "$MY_TG_ID" ] || [ -z "$POSTGRES_USER" ] || [ -z "$POSTGRES_PASS" ] || [ -z "$PAYMENTS_TOKEN_RU" ] || [ -z "IN_PRODUCTION" ]; then
        echo "Error: Missing one or more required environment variables."
        exit 1
      fi

pull:
  stage: pull
  when: on_success
  needs:
    - check_vars
  script:
    - git config --global --add safe.directory /usr/migrebot
    - cd /usr/migrebot
    - git pull

build:
  stage: build
  when: on_success
  needs:
    - pull
  script:
    - cd /usr/migrebot
    - docker compose build

start_dbs:
  stage: start_dbs
  when: on_success
  script:
    - cd /usr/migrebot
    - docker compose up -d migraine_db
    - docker compose up -d redis

migration:
  stage: migration
  when: manual
  script:
    - cd /usr/migrebot
    - docker compose run migrebot alembic upgrade head

test:
  stage: test
  when: manual
  script:
    - cd /usr/migrebot
    - docker compose run migrebot pytest --verbose

run:
  stage: run
  when: manual
  script:
    - cd /usr/migrebot
    - docker compose up -d migrebot
