stages:
  - check_vars
  - pull
  - build
  - copy_db
  - test
  - run

check_vars:
  stage: check_vars
  script:
    - |
      if [ -z "$API_TOKEN" ] || [ -z "$RABBITMQ_USER" ] || [ -z "$RABBITMQ_PASS" ] || [ -z "$RABBITMQ_HOST" ] || [ -z "$MY_TG_ID" ]; then
        echo "Error: Missing one or more required environment variables."
        exit 1
      fi

pull:
  stage: pull
  when: manual
  script:
    - git config --global --add safe.directory /usr/migrebot
    - cd /usr/migrebot
    - git pull

build:
  stage: build
  when: manual
  script:
    - cd /usr/migrebot
    - docker compose up -d

copy_db:
  stage: copy_db
  when: manual
  rules:
    - exists:
        - '/usr/migrebot/db/sql_app.db'
      when: never
  script:
    - cp /usr/migraine_stat/db/sql_app.db /usr/migrebot/db

test:
  stage: test
  when: manual
  script:
    - docker exec -it migrebot sh -c 'pytest'

run:
  stage: run
  when: manual
  script:
    - docker exec -it migrebot sh -c 'python -m src.main'
