version: '3.8'

services:
  migrebot:
    container_name: migrebot
    restart: always
    build: ./
    stdin_open: true
    tty: true
    environment:
      - API_TOKEN=${API_TOKEN:?err}
      - RABBITMQ_USER=${RABBITMQ_USER:?err}
      - RABBITMQ_PASS=${RABBITMQ_PASS:?err}
      - RABBITMQ_HOST=${RABBITMQ_HOST:?err}
      - MY_TG_ID=${MY_TG_ID:?err}
    volumes:
      - ./db:/usr/migrebot/db

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"