version: '3.8'

services:
  migrebot:
    container_name: migrebot
    restart: always
    depends_on:
      rabbitmq:
        condition: service_started
      db:
        condition: service_started
    build: ./
    command: python -m src.main
    environment:
      - API_TOKEN=${API_TOKEN:?err}
      - RABBITMQ_USER=${RABBITMQ_USER:?err}
      - RABBITMQ_PASS=${RABBITMQ_PASS:?err}
      - RABBITMQ_HOST=${RABBITMQ_HOST:?err}
      - MY_TG_ID=${MY_TG_ID:?err}
      - PAYMENTS_TOKEN_RU=${PAYMENTS_TOKEN_RU:?err}
    volumes:
      - migraine_db:/migrebot/db/db_file

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq-host
    image: rabbitmq:3.12-alpine
    restart: always
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:?err}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:?err}

  db:
    container_name: migraine_db
    image: postgres:15-alpine
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASS:?err}
      - POSTGRES_DB=db_prod

  pgadmin:
    container_name: pgadmin4_container
    depends_on:
      db:
        condition: service_started
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${POSTGRES_USER:?err}@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASS:?err}
    ports:
      - "5434:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data:
  rabbitmq-data: