version: '3.8'

services:
  migrebot:
    container_name: migrebot
    restart: always
    build: ./
    stdin_open: true
    tty: true

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"