version: '3.8'

services:
  migrebot:
    container_name: migrebot
#    restart: always
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_started
    build: ./
    command: python -m src.main
    environment:
      - API_TOKEN=${API_TOKEN:?err}
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASS=${POSTGRES_PASS:?err}
      - MY_TG_ID=${MY_TG_ID}
      - PAYMENTS_TOKEN_RU=${PAYMENTS_TOKEN_RU:?err}
      - IN_PRODUCTION=${IN_PRODUCTION:?err}
    stdin_open: true
    tty: true
    volumes:
      - persistent-data:/usr/persistent_data
    networks:
      - migrebot-network

  redis:
    container_name: redis
    image: redis:7.0.7
    restart: always
    expose:
      - 6379
    networks:
      - migrebot-network

#  rabbitmq:
#    container_name: rabbitmq
#    hostname: rabbitmq-host
#    image: rabbitmq:3.12-alpine
#    env_file:
#      - .env   # Remove for prod
#    volumes:
#      - rabbitmq-data:/var/lib/rabbitmq
#    environment:
#      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:?err}
#      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:?err}

  db:
    container_name: migraine_db
    image: postgres:15-alpine
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASS:?err}
      - POSTGRES_DB=db_prod
    networks:
      - migrebot-network

#  pgadmin:
#    container_name: pgadmin4_container
#    depends_on:
#      db:
#        condition: service_started
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=${POSTGRES_USER:?err}@gmail.com
#      - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASS:?err}
#    ports:
#      - "5434:80"
#    volumes:
#      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  persistent-data:
#  pgadmin-data:
#  rabbitmq-data:

networks:
  migrebot-network: